services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./database.db
    volumes:
      - ./data:/app/data
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]



